< form action = "http://gw.baofoo.com/payindex"
method = "post" > < input type = "hidden"
name = "OrderMoney"
value = "20000" / > < input type = "hidden"
name = "TradeDate"
value = "20150706175850" / > < input type = "hidden"
name = "PageUrl"
value = "http://www.nongfadai.com/" / > < input type = "hidden"
name = "Amount"
value = "1" / > < input type = "hidden"
name = "ReturnUrl"
value = "http://www.nongfadai.com/pay/baofu/baoFuChargeRetServlet.htm" / > < input type = "hidden"
name = "AdditionalInfo"
value = "" / > < input type = "hidden"
name = "MemberID"
value = "425926" / > < input type = "hidden"
name = "Signature"
value = "1220081143782b0d05be21837ff56884" / > < input type = "hidden"
name = "InterfaceVersion"
value = "4.0" / > < input type = "hidden"
name = "KeyType"
value = "1" / > < input type = "hidden"
name = "TransID"
value = "bf_63084_20150706175" / > < input type = "hidden"
name = "NoticeType"
value = "0" / > < input type = "hidden"
name = "Username"
value = "" / > < input type = "hidden"
name = "TerminalID"
value = "23012" / > < input type = "hidden"
name = "ProductName"
value = "" / > < input type = "hidden"
name = "PayID"
value = "3002" / > < /form><script type="text/javascript
">document.forms[0].submit();</script>